{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a6619d99-1892-4003-b793-0cb816a3fa6e",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "Data models representing structured CV information.\n",
    "Single Responsibility: Only holds data, no logic.\n",
    "\"\"\"\n",
    "\n",
    "from __future__ import annotations\n",
    "\n",
    "import json\n",
    "from dataclasses import dataclass, field, asdict\n",
    "from typing import List\n",
    "\n",
    "\n",
    "@dataclass\n",
    "class Education:\n",
    "    \"\"\"Represents one education entry.\"\"\"\n",
    "    degree: str = \"\"\n",
    "    institution: str = \"\"\n",
    "    year: str = \"\"\n",
    "\n",
    "\n",
    "@dataclass\n",
    "class Experience:\n",
    "    \"\"\"Represents one work-experience entry.\"\"\"\n",
    "    role: str = \"\"\n",
    "    company: str = \"\"\n",
    "    duration: str = \"\"\n",
    "    summary: str = \"\"\n",
    "\n",
    "\n",
    "@dataclass\n",
    "class Project:\n",
    "    \"\"\"Represents one project entry with its associated skills.\"\"\"\n",
    "    name: str = \"\"\n",
    "    skills: List[str] = field(default_factory=list)\n",
    "\n",
    "\n",
    "@dataclass\n",
    "class CVData:\n",
    "    \"\"\"\n",
    "    Top-level model that holds every piece of information\n",
    "    extracted from a CV / résumé.\n",
    "    \"\"\"\n",
    "    full_name: str = \"\"\n",
    "    phone_number: str = \"\"\n",
    "    email: str = \"\"\n",
    "    location: str = \"\"\n",
    "    education: List[Education] = field(default_factory=list)\n",
    "    skills: List[str] = field(default_factory=list)\n",
    "    experience: List[Experience] = field(default_factory=list)\n",
    "    projects: List[Project] = field(default_factory=list)\n",
    "    raw_text: str = \"\"                       # kept for debugging / re-processing\n",
    "    parser_used: str = \"\"                    # which parser produced the text\n",
    "\n",
    "    # ── helpers ────────────────────────────────────────────\n",
    "    def to_dict(self) -> dict:\n",
    "        \"\"\"Convert to a plain dictionary (excludes raw_text for cleanliness).\"\"\"\n",
    "        data = asdict(self)\n",
    "        data.pop(\"raw_text\", None)           # raw text is bulky; drop it\n",
    "        return data\n",
    "\n",
    "    def to_json(self, indent: int = 2) -> str:\n",
    "        \"\"\"Serialize to a JSON string.\"\"\"\n",
    "        return json.dumps(self.to_dict(), indent=indent, ensure_ascii=False)\n",
    "\n",
    "    @property\n",
    "    def total_skills(self) -> int:\n",
    "        return len(self.skills)\n",
    "\n",
    "    @property\n",
    "    def total_projects(self) -> int:\n",
    "        return len(self.projects)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
